server:
  port: 8081
  servlet:
    context-path: /api/
spring:
  # 数据库连接池
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mysql://hk-cdb-h9rku77n.sql.tencentcdb.com:63917/lottery10?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
      username: root
      password: _+-,2&=!JJ@#$%^*()
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      stat-view-servlet:
        login-username: admin
        login-password: qaz1234qwer
    platform: mariadb
  # Redis 相关信息配置
  redis:
    host: 43.132.194.136
    port: 6379
    password: '*&^%qwer'
    database: 10
    timeout: 60000
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
# 驼峰到下划线自动切换
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
#logback根目录
loghome: /opt/apiend
swagger:
  enable: false